name: finance
dependencies:
  - python=3.6
  - scrapy
  - pip:
    - requests
    - pymysql
    - tqdm
    - emoji
    - tiingo[pandas]
    - cryptocompy
    - openpyxl
    - pandas
    - pyecharts
    - textblob
    - flask
    - pylint
    - yapf
